---
title: "fin_paper"
output: github_document
---

```{r}
library(foreign)
library(tidyverse)
library(lubridate)
```

```{r}
IN_SENATE = function(sen_or_house) sen_or_house == 8
IN_HOUSE = function(sen_or_house) sen_or_house == 9
GUESS_DAY = function(day) ifelse(is.na(day),2,day)
DEM_PARTY_CODE = 100
REP_PARTY_CODE = 200
is_dem = function(code) ifelse(code=="DEM",1,0)
```

```{r}
data = read.dta("state-legislative-data/SLERs1967to2015_20160912b_NV.dta")

tables = lapply(data,function(x)table(x,useNA="ifany"))
info_densty = lapply(tables,dim)
tables["v09z"]


named_data = data %>%
  rename(ELECTION_YEAR=v05,
         ELECTION_MONTH=v06,
         ELECTION_DAY=v06b,
         SENATE_OR_HOUSE=v07,
         DISTRICT_NAME=v08,
         ALT_DISTRICT_NAME=v08z,
         DISTRICT_NUM=v09,
         ALT_DISTRICT_NUM=v09z,
         DISTRICT_TYPE=v12,
         NUM_WINNERS_FOR_POS=v13,
         TERM_LENGTH_BY_LAW=v14,
         TERM_LENGTH_ACTUAL=v15,
         ELECTION_TYPE=v16,
         ELECTION_DETERMINES_SITTING_LEG=v17,
         ELECTION_DETERMINES_SITTING_LEG_GEN=v17b,
         CANIDATE_ID=v18,
         PARTY_CODE_DETAILED=v20,
         PARTY_CODE_SIMPLIFIED=v21,
         INCUMBENCY_DUMMY=v22,
         CANIDATE_VOTE_TOTAL=v23,
         ELECTION_WINNER=v24) %>%
  mutate(election_full_date = as.Date(ISOdate(ELECTION_YEAR,ELECTION_MONTH,GUESS_DAY(ELECTION_DAY))),
         party_code = ifelse(PARTY_CODE_SIMPLIFIED == DEM_PARTY_CODE,"DEM",
                           ifelse(PARTY_CODE_SIMPLIFIED == REP_PARTY_CODE,"REP",
                                                                           "OTHER")))

general_election_data = named_data %>%
  filter(ELECTION_DETERMINES_SITTING_LEG==1)

house_data = filter(general_election_data,IN_HOUSE(SENATE_OR_HOUSE))

#table(house_data$election_full_date)
#table(named_data$SENATE_OR_HOUSE,useNA="ifany")
```

```{r load_economic_data}
folder = "state-legislative-data/Economic Data/"
filename = "Nevada Annual Real Median Househod Income Data 1984-2017 BEA code MEHOINUSNVA672N.csv"
path = paste(folder, filename,sep="")
economic_data = read_csv(path) %>%
  rename(MED_HOUSE_INCOME = MEHOINUSNVA672N) %>%
  mutate(YEAR = as.integer(format(DATE,"%Y")))
```

```{r}
use_data = house_data %>%
  select(ELECTION_WINNER,
         ELECTION_YEAR,
         party_code,
         INCUMBENCY_DUMMY,
         CANIDATE_VOTE_TOTAL,
         DISTRICT_NUM)

with_economic = left_join(use_data,economic_data,by=c("ELECTION_YEAR"="YEAR"))
```

```{r}
beforeyear = 2014

train_data = use_data %>%
  filter(ELECTION_YEAR < beforeyear) %>%
  filter(ELECTION_YEAR > 1970) %>% # we don't have district numbers for 1968 and 1970! (this should be fixable)
  group_by(DISTRICT_NUM,ELECTION_YEAR) %>%
  mutate(percent_vote = CANIDATE_VOTE_TOTAL/sum(CANIDATE_VOTE_TOTAL)) %>%
  ungroup()

pred_perc = lm(percent_vote ~ INCUMBENCY_DUMMY,data=train_data)
```

```{r}
with_economic %>%
  filter(ELECTION_WINNER==1) %>%
  group_by(ELECTION_YEAR) %>%
  summarize(perc_seats_dem = sum(is_dem(party_code)),
            MED_HOUSE_INCOME=mean(MED_HOUSE_INCOME)) %>%
  mutate(perc_seats_dem = perc_seats_dem/perc_seats_dem[1],
         MED_HOUSE_INCOME = MED_HOUSE_INCOME/MED_HOUSE_INCOME[12]) %>%
  gather(Type,Val,-ELECTION_YEAR) %>%
  ggplot(aes(x=ELECTION_YEAR,y=Val,col=Type))+geom_line()
  
```


Road citation:

Gary King; Bradley Palmquist; Greg Adams; Micah Altman;
Kenneth Benoit; Claudine Gay; Jeffrey B. Lewis; Russ Mayer;
and Eric Reinhardt. 1997. "The Record of American Democracy, 1984-1990," Harvard University, Cambridge, MA [producer],
Ann Arbor, MI: ICPSR [distributor].